<a href="https://colab.research.google.com/github/veeraswamy87/Java-Project-Git-Maven-Docker/blob/master/Python_Basic_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Concat Two Tuples

In [8]:
tup1 = ("Veeraswamy", 2 ,True)

In [6]:
tup2 = ("Gatta", 3 ,False)

In [9]:
tup1 + tup2

('Veeraswamy', 2, True, 'Gatta', 3, False)

NumPy

In [12]:
import numpy as np
n1=np.zeros((5,5))
print(n1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


What is Pandas 

It deals with large variety of data and its open source library

it provides two  fantastic data structures ( Series and DataFames)

Dataframes - its mutable data type present in pandas library and provides support for heterogeneous data

In [17]:
import pandas as pd

df = pd.read_csv("/content/sample_data/california_housing_test.csv")
df.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0

In [19]:
import pandas as pd

data = ["1", "two","3.5","4"]

series = pd.Series(data)
print(series)
print(type(series))

0      1
1    two
2    3.5
3      4
dtype: object
<class 'pandas.core.series.Series'>


In [23]:
import pandas as pd

df = pd.DataFrame({ "Name": ["veeraswamy","siva","sravan","nandhu"], "Age":[35,35,6,5]})

print(df)

df.groupby("Age").count()


         Name  Age
0  veeraswamy   35
1        siva   35
2      sravan    6
3      nandhu    5


Name
Age      
5       1
6       1
35      2

In [25]:
import pandas as pd

df =pd.DataFrame()

names = ['Veera','Siva','Sravan','Nandhu']

year = [1988,1988,2016,2018]

df['names']=names
df['year']=year

print(df)

    names  year
0   Veera  1988
1    Siva  1988
2  Sravan  2016
3  Nandhu  2018


In [26]:
import pandas as pd


names = ['Veera','Siva','Sravan','Nandhu']

year = [1988,1988,2016,2018]

d={'names':names,"year":year}

df =pd.DataFrame(d)

print(df)

    names  year
0   Veera  1988
1    Siva  1988
2  Sravan  2016
3  Nandhu  2018


Dictonary :   {}    {key:value,key:value}

List :  []   ["value","value"]

Tupe : ()   ("value",'value')

Pandas support left,right,inner and outer join and its horizontal stacking

For vertical stacking ,need to use contact method